In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("Dataset/NIFTY50_all.csv")
print(df.head())

         Date      Symbol Series  Prev Close    Open     High    Low   Last  \
0  2007-11-27  MUNDRAPORT     EQ      440.00  770.00  1050.00  770.0  959.0
1  2007-11-28  MUNDRAPORT     EQ      962.90  984.00   990.00  874.0  885.0
2  2007-11-29  MUNDRAPORT     EQ      893.90  909.00   914.75  841.0  887.0
3  2007-11-30  MUNDRAPORT     EQ      884.20  890.00   958.00  890.0  929.0
4  2007-12-03  MUNDRAPORT     EQ      921.55  939.75   995.00  922.0  980.0

    Close    VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  962.90  984.72  27294366  2.687719e+15     NaN           9859619.0
1  893.90  941.38   4581338  4.312765e+14     NaN           1453278.0
2  884.20  888.09   5124121  4.550658e+14     NaN           1069678.0
3  921.55  929.17   4609762  4.283257e+14     NaN           1260913.0
4  969.30  965.65   2977470  2.875200e+14     NaN            816123.0

   %Deliverble
0       0.3612
1       0.3172
2       0.2088
3       0.2735
4       0.2741

In [4]:
df.shape
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 235192 entries, 0 to 235191
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                235192 non-null  str
 1   Symbol              235192 non-null  str
 2   Series              235192 non-null  str
 3   Prev Close          235192 non-null  float64
 4   Open                235192 non-null  float64
 5   High                235192 non-null  float64
 6   Low                 235192 non-null  float64
 7   Last                235192 non-null  float64
 8   Close               235192 non-null  float64
 9   VWAP                235192 non-null  float64
 10  Volume              235192 non-null  int64
 11  Turnover            235192 non-null  float64
 12  Trades              120344 non-null  float64
 13  Deliverable Volume  219115 non-null  float64
 14  %Deliverble         219115 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 26.9 MB

,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
count,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.00000,2.351920e+05,2.351920e+05,1.203440e+05,2.191150e+05,219115.000000
mean,1266.196349,1267.759708,1286.581440,1247.488465,1266.388302,1266.554351,1267.13230,3.045903e+06,1.610138e+14,6.196427e+04,1.315098e+06,0.502997
std,2581.370320,2585.259609,2619.649216,2546.621396,2581.392543,2582.140942,2582.69998,7.333981e+06,3.298085e+14,6.866457e+04,2.831670e+06,0.190019
min,0.000000,8.500000,9.750000,8.500000,9.100000,9.150000,9.21000,3.000000e+00,1.047000e+07,1.100000e+01,5.000000e+00,0.023600
25%,274.300000,275.000000,279.500000,269.600000,274.400000,274.350000,274.69750,2.190095e+05,1.612816e+13,2.183400e+04,1.253830e+05,0.364700
50%,566.500000,567.025000,576.900000,556.500000,567.000000,566.700000,566.94000,1.010938e+06,6.832603e+13,4.406800e+04,5.017560e+05,0.511000
75%,1242.200000,1243.312500,1263.000000,1221.650000,1242.900000,1242.400000,1242.66250,3.019851e+06,1.863835e+14,7.893550e+04,1.452233e+06,0.638400
max,32861.950000,33399.950000,33480.000000,32468.100000,32849.000000,32861.950000,32975.24000,4.810589e+08,3.564334e+16,1.643015e+06,2.325307e+08,1.000000

In [5]:
df["Symbol"].unique()

<StringArray>
['MUNDRAPORT', 'ADANIPORTS', 'ASIANPAINT',    'UTIBANK',   'AXISBANK',
 'BAJAJ-AUTO', 'BAJAJFINSV', 'BAJAUTOFIN', 'BAJFINANCE',     'BHARTI',
 'BHARTIARTL',       'BPCL',  'BRITANNIA',      'CIPLA',  'COALINDIA',
    'DRREDDY',  'EICHERMOT',       'GAIL',     'GRASIM',    'HCLTECH',
       'HDFC',   'HDFCBANK',  'HEROHONDA', 'HEROMOTOCO',   'HINDALC0',
   'HINDALCO',  'HINDLEVER', 'HINDUNILVR',  'ICICIBANK', 'INDUSINDBK',
 'INFOSYSTCH',       'INFY',        'IOC',        'ITC',     'JSWSTL',
   'JSWSTEEL',   'KOTAKMAH',  'KOTAKBANK',         'LT',        'M&M',
     'MARUTI',  'NESTLEIND',       'NTPC',       'ONGC',  'POWERGRID',
   'RELIANCE',       'SBIN',   'SHREECEM',  'SUNPHARMA',      'TELCO',
 'TATAMOTORS',      'TISCO',  'TATASTEEL',        'TCS',      'TECHM',
      'TITAN', 'ULTRACEMCO',    'UNIPHOS',        'UPL',    'SESAGOA',
       'SSLT',       'VEDL',      'WIPRO',    'ZEETELE',       'ZEEL']
Length: 65, dtype: str

In [6]:
df.tail()

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
235187,2021-04-26,ZEEL,EQ,188.00,190.6,191.10,185.10,186.70,186.40,187.35,8542755,1.600451e+14,52374.0,2340188.0,0.2739
235188,2021-04-27,ZEEL,EQ,186.40,188.0,192.95,186.80,188.80,188.15,189.41,14247767,2.698636e+14,73673.0,5425957.0,0.3808
235189,2021-04-28,ZEEL,EQ,188.15,188.8,190.60,187.10,188.95,189.10,188.85,8429439,1.591917e+14,44056.0,2413974.0,0.2864
235190,2021-04-29,ZEEL,EQ,189.10,190.8,191.65,186.00,186.60,186.55,187.44,9483009,1.777471e+14,60932.0,2744472.0,0.2894
235191,2021-04-30,ZEEL,EQ,186.55,185.3,190.95,183.65,185.00,185.60,187.53,11435285,2.144440e+14,62607.0,3323909.0,0.2907

In [7]:
df.head()
df.tail()
df.nunique()

Date                    5306
Symbol                    65
Series                     1
Prev Close             63729
Open                   44298
High                   49036
Low                    51335
Last                   48570
Close                  63739
VWAP                  138831
Volume                220434
Turnover              235184
Trades                 79112
Deliverable Volume    199963
%Deliverble             9456
dtype: int64

In [9]:
print(df["Date"].nunique())

5306

In [10]:
print(df['Date'].min())
print(df['Date'].max())

2000-01-03
2021-04-30

In [11]:
df.groupby('Date')['Symbol'].nunique().describe()

count    5306.000000
mean       44.325669
std         6.205547
min        28.000000
25%        42.000000
50%        48.000000
75%        49.000000
max        49.000000
Name: Symbol, dtype: float64

In [12]:
df.groupby('Symbol')['Date'].count().sort_values()

Symbol
JSWSTL         123
SSLT           388
KOTAKMAH       502
TELCO          999
MUNDRAPORT    1023
              ...
RELIANCE      5306
SUNPHARMA     5306
TITAN         5306
BPCL          5306
WIPRO         5306
Name: Date, Length: 65, dtype: int64

In [13]:
print(df.columns.tolist())

['Date', 'Symbol', 'Series', 'Prev Close', 'Open', 'High', 'Low', 'Last', 'Close', 'VWAP', 'Volume', 'Turnover', 'Trades', 'Deliverable Volume', '%Deliverble']

In [14]:
df.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                114848
Deliverable Volume     16077
%Deliverble            16077
dtype: int64

In [15]:
import yfinance as yf

data = yf.download(
    "RELIANCE.NS",
    start="2021-05-01",
    end="2026-09-13"
)

print(data.columns)
print(data.head())
print(data.info())

[*********************100%***********************]  1 of 1 completed

MultiIndex([( 'Close', 'RELIANCE.NS'),
            (  'High', 'RELIANCE.NS'),
            (   'Low', 'RELIANCE.NS'),
            (  'Open', 'RELIANCE.NS'),
            ('Volume', 'RELIANCE.NS')],
           names=['Price', 'Ticker'])
Price            Close        High         Low        Open      Volume
Ticker     RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS RELIANCE.NS
Date
2021-05-03  884.206360  893.210669  877.007437  887.343178    23640186
2021-05-04  865.046631  888.155516  862.519150  880.121562    21849830
2021-05-05  866.626404  874.931121  861.187681  868.093276    12393609
2021-05-06  871.546143  873.351529  860.533314  867.416347    14624666
2021-05-07  871.884583  882.671714  869.289351  874.592632    12288548
<class 'pandas.DataFrame'>
DatetimeIndex: 1332 entries, 2021-05-03 to 2026-09-11
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, RELIANCE.NS)   1332 non-null   float64
 1   (High, RELIANCE.NS)    1332 non-null   float64
 2   (Low, RELIANCE.NS)     1332 non-null   float64
 3   (Open, RELIANCE.NS)    1332 non-null   float64
 4   (Volume, RELIANCE.NS)  1332 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 62.4 KB
None

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 235192 entries, 0 to 235191
Data columns (total 15 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Date                235192 non-null  str
 1   Symbol              235192 non-null  str
 2   Series              235192 non-null  str
 3   Prev Close          235192 non-null  float64
 4   Open                235192 non-null  float64
 5   High                235192 non-null  float64
 6   Low                 235192 non-null  float64
 7   Last                235192 non-null  float64
 8   Close               235192 non-null  float64
 9   VWAP                235192 non-null  float64
 10  Volume              235192 non-null  int64
 11  Turnover            235192 non-null  float64
 12  Trades              120344 non-null  float64
 13  Deliverable Volume  219115 non-null  float64
 14  %Deliverble         219115 non-null  float64
dtypes: float64(11), int64(1), str(3)
memory usage: 26.9 MB

In [19]:
df.isnull().sum()

Date                       0
Symbol                     0
Series                     0
Prev Close                 0
Open                       0
High                       0
Low                        0
Last                       0
Close                      0
VWAP                       0
Volume                     0
Turnover                   0
Trades                114848
Deliverable Volume     16077
%Deliverble            16077
dtype: int64

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df['Date'] = pd.to_datetime(df['Date'])

df.groupby('Symbol')['Date'].agg(['min', 'max', 'count']).sort_values('count')

                  min        max  count
Symbol
JSWSTL     2005-03-23 2005-09-15    123
SSLT       2013-10-04 2015-05-06    388
KOTAKMAH   2000-01-03 2003-04-17    502
TELCO      2000-01-03 2003-12-24    999
MUNDRAPORT 2007-11-27 2012-01-16   1023
...               ...        ...    ...
RELIANCE   2000-01-03 2021-04-30   5306
SUNPHARMA  2000-01-03 2021-04-30   5306
TITAN      2000-01-03 2021-04-30   5306
BPCL       2000-01-03 2021-04-30   5306
WIPRO      2000-01-03 2021-04-30   5306

[65 rows x 3 columns]

In [22]:
df = df.sort_values(['Symbol', 'Date'])

print(df[['Symbol', 'Date']].head(20))

          Symbol       Date
1023  ADANIPORTS 2012-01-17
1024  ADANIPORTS 2012-01-18
1025  ADANIPORTS 2012-01-19
1026  ADANIPORTS 2012-01-20
1027  ADANIPORTS 2012-01-23
1028  ADANIPORTS 2012-01-24
1029  ADANIPORTS 2012-01-25
1030  ADANIPORTS 2012-01-27
1031  ADANIPORTS 2012-01-30
1032  ADANIPORTS 2012-01-31
1033  ADANIPORTS 2012-02-01
1034  ADANIPORTS 2012-02-02
1035  ADANIPORTS 2012-02-03
1036  ADANIPORTS 2012-02-06
1037  ADANIPORTS 2012-02-07
1038  ADANIPORTS 2012-02-08
1039  ADANIPORTS 2012-02-09
1040  ADANIPORTS 2012-02-10
1041  ADANIPORTS 2012-02-13
1042  ADANIPORTS 2012-02-14

In [23]:
df.duplicated(subset=['Date', 'Symbol']).sum()

np.int64(0)

In [24]:
df[['Prev Close', 'Open', 'High', 'Low', 'Close', 'VWAP', 'Volume', 'Turnover']].describe()

,Prev Close,Open,High,Low,Close,VWAP,Volume,Turnover
count,235192.000000,235192.000000,235192.000000,235192.000000,235192.000000,235192.00000,2.351920e+05,2.351920e+05
mean,1266.196349,1267.759708,1286.581440,1247.488465,1266.554351,1267.13230,3.045903e+06,1.610138e+14
std,2581.370320,2585.259609,2619.649216,2546.621396,2582.140942,2582.69998,7.333981e+06,3.298085e+14
min,0.000000,8.500000,9.750000,8.500000,9.150000,9.21000,3.000000e+00,1.047000e+07
25%,274.300000,275.000000,279.500000,269.600000,274.350000,274.69750,2.190095e+05,1.612816e+13
50%,566.500000,567.025000,576.900000,556.500000,566.700000,566.94000,1.010938e+06,6.832603e+13
75%,1242.200000,1243.312500,1263.000000,1221.650000,1242.400000,1242.66250,3.019851e+06,1.863835e+14
max,32861.950000,33399.950000,33480.000000,32468.100000,32861.950000,32975.24000,4.810589e+08,3.564334e+16

In [25]:
(df['Prev Close'] == 0).sum()

np.int64(1)

In [26]:
df[df['Prev Close'] == 0][['Date', 'Symbol', 'Prev Close', 'Open', 'Close']]

            Date  Symbol  Prev Close  Open  Close
25572 2002-02-18  BHARTI         0.0  51.9  44.35

In [27]:
df[df['Symbol'] == 'BHARTI'].loc[:, ['Date', 'Prev Close', 'Close']].head(10)

            Date  Prev Close  Close
25572 2002-02-18        0.00  44.35
25573 2002-02-19       44.35  41.70
25574 2002-02-20       41.70  41.25
25575 2002-02-21       41.25  42.40
25576 2002-02-22       42.40  43.30
25577 2002-02-25       43.30  42.80
25578 2002-02-26       42.80  43.60
25579 2002-02-27       43.60  44.65
25580 2002-02-28       44.65  41.50
25581 2002-03-01       41.50  42.50

In [28]:
for col in ['Open', 'High', 'Low', 'Close', 'VWAP']:
    print(col, (df[col] <= 0).sum())

Open 0
High 0
Low 0
Close 0
VWAP 0

In [29]:
df['Series'].value_counts()

Series
EQ    235192
Name: count, dtype: int64

In [30]:
(df.isna().sum() / len(df) * 100).round(2)

Date                   0.00
Symbol                 0.00
Series                 0.00
Prev Close             0.00
Open                   0.00
High                   0.00
Low                    0.00
Last                   0.00
Close                  0.00
VWAP                   0.00
Volume                 0.00
Turnover               0.00
Trades                48.83
Deliverable Volume     6.84
%Deliverble            6.84
dtype: float64

In [31]:
df.groupby('Date')['Symbol'].nunique().describe()

count    5306.000000
mean       44.325669
std         6.205547
min        28.000000
25%        42.000000
50%        48.000000
75%        49.000000
max        49.000000
Name: Symbol, dtype: float64

In [32]:
df.groupby('Symbol')['Date'].agg(['min', 'max', 'count']).sort_values('count')

                  min        max  count
Symbol
JSWSTL     2005-03-23 2005-09-15    123
SSLT       2013-10-04 2015-05-06    388
KOTAKMAH   2000-01-03 2003-04-17    502
TELCO      2000-01-03 2003-12-24    999
MUNDRAPORT 2007-11-27 2012-01-16   1023
...               ...        ...    ...
RELIANCE   2000-01-03 2021-04-30   5306
SUNPHARMA  2000-01-03 2021-04-30   5306
TITAN      2000-01-03 2021-04-30   5306
BPCL       2000-01-03 2021-04-30   5306
WIPRO      2000-01-03 2021-04-30   5306

[65 rows x 3 columns]

In [33]:
df['Symbol'].nunique()

65

In [34]:
df.groupby('Symbol')['Date'].count().sort_values(ascending=False).head(15)

Symbol
ASIANPAINT    5306
SUNPHARMA     5306
GRASIM        5306
CIPLA         5306
BPCL          5306
DRREDDY       5306
IOC           5306
HDFCBANK      5306
HDFC          5306
ICICIBANK     5306
ITC           5306
WIPRO         5306
TITAN         5306
ONGC          5306
RELIANCE      5306
Name: Date, dtype: int64